### ISSUE TITLE
License needed

### ISSUE THREAD

**Issue by ellenwiger** [norkorr/edvard_munchs_tekster#1]
Find the right license and add to repo.

**Comment by hildeboee** [comment]
How do I add a license? We are using https://creativecommons.org/licenses/by/4.0/ at emunch.no

**Comment by arockenberger** [comment]
Go to this website (https://choosealicense.com/non-software/) and choose the license you want (CC BY). Then click "Copy license text to clipboard" in the upper right corner. You can add a new file to the repository and paste the license text. The file extension should be .txt. GitHub will automatically read this as the correct license text and tag your repository with CC BY 4.0!
